Andy userapi
olioapps/typescript-starter-lab pull request #35
Opened 2022-06-09 19:06 UTC by Plymatea

2022-06-09 23:22 UTC, DuHerb commented on .vscode/launch.json
> +}
new line

2022-06-09 23:36 UTC, DuHerb requested changes

2022-06-09 23:36 UTC, DuHerb commented on src/index.test.ts
> +    const seedUsers: Array<IUser> = [{
if `seedUsers` is used multiple times, it is ok for it to be defined in a scope available for all tests that need it.

2022-06-09 23:36 UTC, DuHerb commented on src/index.test.ts
> +    const x = new UserAPI(seedUsers)
do not use letters as const names.  Variable names should be descriptive.  `userApi` totally acceptable and instantly understood.

2022-06-09 23:36 UTC, DuHerb commented on src/index.test.ts
> +    expect(x.getUsers()).toEqual(seedUsers)
define the `expect` and `toEqual` arguments as constants and then pass them.  Readability and Olio conventions.  

Exceptions for simple input/output, like a single string, boolean, or number.

2022-06-09 23:36 UTC, DuHerb commented on src/index.test.ts
> +        name: "andy",
weird indentation

2022-06-09 23:36 UTC, DuHerb commented on src/index.test.ts
> +      id: "1",
indentation

2022-06-09 23:36 UTC, DuHerb commented on src/index.test.ts
> +      id: "1",
find all cases of this.

Tip: to avoid this repition, "Andy" can be defined somewhere else as `defaultUser`.  if you need another user with a different property, just spread some new values into `defaultUser` and build your lists that way.

2022-06-09 23:36 UTC, DuHerb commented on src/index.test.ts
> +    x.addUser(user3)
why not just add all the users into the original list when you create the userAPI?  this is confusing.

2022-06-09 23:36 UTC, DuHerb commented on src/index.test.ts
>  })
new line

2022-06-09 23:36 UTC, DuHerb commented on src/index.test.ts
> +    const newUser3 = x.addUser(user3)
over complicated.  just create your three users, put them in a list.  pass that to the api constructor.  then define the expected array of users.

2022-06-10 17:42 UTC, Plymatea commented on .vscode/launch.json
> +}
New line entered as line 30

2022-06-10 18:24 UTC, Plymatea commented on src/index.test.ts
> +    const seedUsers: Array<IUser> = [{
Moved the `seesUsers` scope and dried the code up.

2022-06-10 18:25 UTC, Plymatea commented on src/index.test.ts
> +    const x = new UserAPI(seedUsers)
replaced all instances of `x` with `userAPI`

2022-06-10 18:26 UTC, Plymatea commented on src/index.test.ts
> +    expect(x.getUsers()).toEqual(seedUsers)
Done

2022-06-10 18:26 UTC, Plymatea commented on src/index.test.ts
> +        name: "andy",
Fixed

2022-06-10 18:26 UTC, Plymatea commented on src/index.test.ts
> +      id: "1",
done

2022-06-10 18:26 UTC, Plymatea commented on src/index.test.ts
> +    x.addUser(user3)
Fixed

2022-06-10 18:27 UTC, Plymatea commented on src/index.test.ts
>  })
Fixed

2022-06-10 18:27 UTC, Plymatea commented on src/index.test.ts
> +    const newUser3 = x.addUser(user3)
Fixed

2022-06-10 19:23 UTC, DuHerb approved these changes

2022-06-10 19:23 UTC, DuHerb commented on src/index.test.ts
> +    it("addUser() throws error when duplicating user info", () => {
empty lines should separate `it` blocks.  strictly readability.

2022-06-10 19:23 UTC, DuHerb commented on src/index.ts
> +}
new line error

2022-06-10 20:37 UTC, DuHerb requested changes

2022-06-10 20:37 UTC, DuHerb commented on src/index.test.ts
> +    it("addUser() throws error when duplicating user info", () => {
please apply to all tests.

2022-06-10 20:47 UTC, Plymatea commented on src/index.ts
> +}
Done

2022-06-10 20:47 UTC, Plymatea commented on src/index.test.ts
> +    it("addUser() throws error when duplicating user info", () => {
Done

2022-06-10 21:25 UTC, merged