Add jest tests for all methods, add immutability to methods
olioapps/typescript-starter-lab pull request #36
Opened 2022-06-09 19:14 UTC by dlinds

**Ticket**
Not applicable

**What does this PR do**
- Immutability has been added to all methods
- Writes Jest tests for all methods
- Removes original console.log tests

**Media**
![image](https://user-images.githubusercontent.com/7016167/172925543-5250e626-cc26-45f6-8d89-f3e262aa3153.png)

**How to test**
To test, clone the repository to your computer and navigate to the project with the terminal. Download all necessary packages with **_yarn install_** and when ready, run **_yarn run test_** to execute the application. You should see several tests and the results of these tests.

2022-06-09 23:21 UTC, DuHerb requested changes

2022-06-09 23:21 UTC, DuHerb commented on src/index.test.ts
> +describe('new UserAPI()', () => {
organizational nit pick (just my own preference, no change required).
I would nest ALL subsequent `describe` blocks in this one.  (describes can be nested inside each other)

2022-06-09 23:21 UTC, DuHerb commented on src/index.test.ts
> +  it("should confirm x is a UserAPI object", () => {
this test should be wrapped in it's own `describe` as something like `describe("UserApi constructor"...)...`.  Then you have tests for:

- do you get an instance of UserApi (as seen here)?
- when called with no argument, does get users return an empty list?
- when called with an argument (list of users), does getUsers immediately return the expected list?

2022-06-09 23:21 UTC, DuHerb commented on src/index.test.ts
> +    const x = new UserAPI([{ name: 'Larry', favoriteColor: 'gray', age: 544, id: "1" }])
avoid naming variable arbitrary letters.  variable names should describe the thing.

2022-06-09 23:21 UTC, DuHerb commented on src/index.test.ts
> +    expect(x.addUser({ name: 'Daniel', favoriteColor: 'purple', age: 33 }))
for clarity, Olio generally prefers if `expected` and `actual` arguments are defined as constants, rather than have values passed directly into the `expect` and `toEqual` functions.

2022-06-09 23:21 UTC, DuHerb commented on src/index.test.ts
> +    expect(x.getUsers())
this test is doing something other than what is described.  Should be wrapped in it's own `it`, or moved into the the `getUsers` describe block

2022-06-09 23:21 UTC, DuHerb commented on src/index.test.ts
> +    expect(x.getUsers())
again, should be in it's own test block, as it is fundamentally different test from 'delete user returns deleted user`

2022-06-09 23:21 UTC, DuHerb commented on src/index.test.ts
> +    expect(x.getUsers())
unnecessary

2022-06-09 23:21 UTC, DuHerb commented on src/index.test.ts
> +    expect(x.getUsers())
unnecessary.  this is covered in a different test

2022-06-09 23:21 UTC, DuHerb commented on src/index.test.ts
> +      .toEqual([
same

2022-06-09 23:21 UTC, DuHerb commented on src/index.test.ts
> +    expect(x.getUsers())
same

2022-06-09 23:34 UTC, dlinds commented on src/index.test.ts
> +    expect(x.addUser({ name: 'Daniel', favoriteColor: 'purple', age: 33 }))
Thanks! Just to be sure, you're referring to jest.spyOn right? That is fixed in the new code with objects. For the above - I wasn't sure how to get it to work with the arrays, as the ID was being generated was with Date.now(), and would return an object with an ID that I wouldn't know before making the test.

2022-06-09 23:34 UTC, DuHerb requested changes

2022-06-09 23:34 UTC, DuHerb commented on src/index.test.ts
> +    expect(x.getUsers())
testing the exception, not getUsers

2022-06-09 23:38 UTC, dlinds commented on src/index.test.ts
> +    expect(x.getUsers())
Thanks! I've got them removed now. I figured I would be extra cautious and confirm that it was actually removing it from the array. 

Is there a correct way to test that the array has been correctly modified? Would I just move my _new userAPI()_ instantiation outside of the it()? Or should I just be avoiding it all together?

2022-06-10 17:55 UTC, DuHerb requested changes

2022-06-10 17:55 UTC, DuHerb commented on src/index.test.ts
> +    it("should delete one user and return deleted user", () => {
should also expect the returned use to equal `{ name: 'Larry', favoriteColor: 'gray', age: 544, id: "1" }`

2022-06-10 17:55 UTC, DuHerb commented on src/index.test.ts
> +    it("should return array of two DaNIeL users (ignore letter case)", () => {
change not necessary, but the descriptions should be slightly more generic....ie `search ignores letter case`

2022-06-10 17:55 UTC, DuHerb commented on src/index.test.ts
> +        .toEqual([
Olio convention would be to define `actual` and `expected` constants.  this is strictly for readability/clarity.

so your testing statements would look like:
`expect(actual).toEqual(expected)`

Exceptions can be made for simple values like booleans, numbers, or short strings.
The way you've done your expections testing is also fine.

For the sake of this exercise, changes aren't necessary.  But future tests should consider this pattern.

2022-06-10 19:11 UTC, DuHerb approved these changes

2022-06-10 19:12 UTC, merged