Convert UserAPI to object, update all tests
olioapps/typescript-starter-lab pull request #37
Opened 2022-06-10 20:52 UTC by dlinds

**Ticket**
N/A

**What this PR does**
This PR converts all code from the _**_users**_ array into an object and stores all values with keys. Tests have been re-written to account for the new code. Tests also conform to Olio standards by using const **_expected_** and _**actual**_ for test blocks.

**Media**
![image](https://user-images.githubusercontent.com/7016167/173134641-0babbede-cb56-4979-9095-6c8a63c332d9.png)

**How to test**
To test, clone the repository to your computer and navigate to the project with the terminal. Download all necessary packages with **_yarn install_** and when ready, run **_yarn run test_** to execute the application. You should see several tests and the results of these tests.

2022-06-10 22:50 UTC, DuHerb requested changes

2022-06-10 22:50 UTC, DuHerb commented on src/index.ts
> +    copyOfAPIUsers[id] = { ...newUser }
instead of `let copyOfAPIUsers`, use the spread operator to copy state, and the new user as `newUsers` in one line.  Let me know if you need help after 15/20 min.

2022-06-10 22:50 UTC, DuHerb commented on src/index.ts
> +      return Object.values({ ...this._users })
don't have to spread `this._users` here.  Object.values won't mutate the object.

2022-06-10 22:50 UTC, DuHerb commented on src/index.ts
> +      const userToDelete = { ...this._users[id] }
don't need to make a copy here.  can just return `this._users[id]`

2022-06-10 22:50 UTC, DuHerb commented on src/index.ts
> +      this._users = { ...updatedArray }
even those updated array is a new object, we can adhere to immutability principles here by using `restructuring` to create new object without the userToBeDeleted in one line.  see `...rest`

let me know if you get stumped before EOD

2022-06-10 22:50 UTC, DuHerb commented on src/index.ts
> +    const userResult = Object.values(copyOfUsers).filter(x => x["name"].toLowerCase() === name.toLowerCase())
don't need to copy users, just iterate on `this._user`. It won't mutate the object.

2022-06-10 22:50 UTC, DuHerb commented on src/index.ts
> +    const userResult = Object.values(copyOfUsers).filter(x => x["favoriteColor"].toLowerCase() === color.toLowerCase())
same.  just use `this._users`

2022-06-10 22:55 UTC, dlinds commented on src/index.ts
> +    copyOfAPIUsers[id] = { ...newUser }
Thanks! Got it

`const copyOfAPIUsers: { [key: string]: IUser } = { ...this._users, [id]: { ...user, id: id } }`

2022-06-10 22:56 UTC, dlinds commented on src/index.ts
> +      return Object.values({ ...this._users })
aw sweet, good to know. Thanks!

2022-06-13 16:44 UTC, DuHerb commented on src/index.ts
> +  constructor(private _users: { [key: string]: IUser } = {}) {
take a look at the TS utility type `Record` and use it here.

2022-06-13 16:44 UTC, DuHerb commented on src/index.ts
> +    if (Object.values(this._users).some(x => x.name.toLowerCase() === user.name.toLowerCase() && x.favoriteColor.toLowerCase() === x.favoriteColor.toLowerCase() && x.age === user.age)) {
for readability, i'd leave all of the `===` statements on separate lines

2022-06-13 18:59 UTC, DuHerb approved these changes

2022-06-13 18:59 UTC, DuHerb commented on src/index.ts
> +      return { ...userToDelete }
don't have to spread `userToDelete` here.  can just pass `userToDelete`.  no change required.

2022-06-13 19:03 UTC, merged