Convert array dataset to object structure
olioapps/typescript-starter-lab pull request #38
Opened 2022-06-10 21:29 UTC by Plymatea

**Ticket**
None

**This Does**
- Refcator index.ts dataset to use object storage instead of array storage
- `getUsers()` still returns an array of users
- Refactor index.test.ts for updated dataset structure

**Media**
- Shows all tests passing

![image](https://user-images.githubusercontent.com/96448051/173153748-bf7a3673-41a4-40fa-af15-ef0c0648e589.png)

**Test**
none

2022-06-10 22:39 UTC, DuHerb requested changes

2022-06-10 22:39 UTC, DuHerb commented on src/index.test.ts
> +      console.log("expected", expected);
kill logs

2022-06-10 22:39 UTC, DuHerb commented on src/index.test.ts
>  const userAPI = new UserAPI(seedUsers)
userApi should be initiated in each different describe block.  Here, your userApi will always have users, which could possibly pollute/affect tests in unexpected ways.

2022-06-10 22:39 UTC, DuHerb commented on src/index.test.ts
>  const userAPI = new UserAPI(seedUsers)
sorry that i missed this previously.

2022-06-10 22:39 UTC, DuHerb commented on src/index.ts
> +    const result = (Object.values(this._users)).filter( existingUser => (
small optimization....
instead of `.filter`, could just use `.some`, returning a boolean.  Or, if you actually need the found item for something, '.find'

2022-06-10 22:39 UTC, DuHerb commented on src/index.ts
> +    const id = Date.now().toString() + Math.floor(Math.random()*100)
consider making a private `getUId` function that provides this value for you.

just a small example of encapsulation.

2022-06-10 22:39 UTC, DuHerb commented on src/index.ts
> +    let newUsersState: any = {...this._users}
`let` ==> `const`, and the newUser can be added to `newUserState` using the spread method, rather than mutating the object (`ln32`)

2022-06-10 22:39 UTC, DuHerb commented on src/index.ts
> +    const foundUser = Object.values(this._users).find( user => user.id === id)
now that were using the object, can just get the user by the id `this._users[id]`.  this is one of the advantages of using an object (or map) for collections.

2022-06-10 22:39 UTC, DuHerb commented on src/index.ts
> +      delete newUserState[id]
even though we are mutating an object we just created, we can still strictly adhere to immutably principles here by using the spread operator.  try using `...rest`, and let me know if you get stuck after more than 15/20 minutes.

2022-06-10 22:39 UTC, DuHerb commented on src/index.ts
> +const seedUsers: Record<string, IUser> = {
if this was for dev....it shouldn't be included in PR

2022-06-10 22:40 UTC, Plymatea commented on src/index.test.ts
> +      console.log("expected", expected);
Damn Sorry. Done

2022-06-10 22:43 UTC, Plymatea commented on src/index.test.ts
>  const userAPI = new UserAPI(seedUsers)
Done

2022-06-10 22:47 UTC, Plymatea commented on src/index.ts
> +    const id = Date.now().toString() + Math.floor(Math.random()*100)
Done

2022-06-10 22:52 UTC, Plymatea commented on src/index.ts
> +    const foundUser = Object.values(this._users).find( user => user.id === id)
Good call! Done

2022-06-10 22:54 UTC, Plymatea commented on src/index.ts
> +const seedUsers: Record<string, IUser> = {
Noticed this after i created the PR. I must have missed pushing the changes back up to github.

2022-06-10 22:56 UTC, Plymatea commented on src/index.ts
> +    const result = (Object.values(this._users)).filter( existingUser => (
nice. changed this.

2022-06-10 22:58 UTC, Plymatea commented on src/index.ts
> +    let newUsersState: any = {...this._users}
Done

2022-06-10 23:40 UTC, Plymatea commented on src/index.ts
> +      delete newUserState[id]
Thank you For the help on this!  Done

2022-06-13 16:40 UTC, DuHerb approved these changes

2022-06-13 16:41 UTC, merged