Emma init user api
olioapps/typescript-starter-lab pull request #60
Opened 2023-08-21 21:05 UTC by emmalgs

## What this is:
Initial user api ticket
* Instantiate UserAPI class
* getAllUsers method

## Ticket
[init user api](https://github.com/olioapps/typescript-starter-lab/issues/58)

## Steps to verify
* in the project directory on the branch 'emma-init-user-api', run ```yarn test```

## Media
![3 tests passing](https://github.com/olioapps/typescript-starter-lab/assets/40610781/c2836f6d-ae0d-4b60-aa3e-dd10ab581407)

## Notes
* I haven't tested maps before, so decided to compare the lengths of the incoming array to the size of the map? Was able to verify they are maps through console.logs. Not sure if this is typical and would appreciate feedback on best ways to test Map.

2023-08-21 22:27 UTC, DuHerb requested changes

2023-08-21 22:27 UTC, DuHerb commented on src/index.ts
> +  readonly favColor: string,
We are sort of simulating a use case where we are using persisted data (eg: database records). these values MAY be updated in the future via an `updateUser` method.  So these should not be `readonly`.

But the instinct is generally correct, especially in regards to client side logic: you want to practice immutability, and enforce this pattern by defining types and their properties as ReadOnly unless it will explicitly need to be changed

2023-08-21 22:27 UTC, DuHerb commented on src/index.ts
> +  constructor(users: User[] = []) {
the constructor should consume a the actual shape of your collection. So, if the users collection is a map, then the UserAPI parameter should be a map of users.

The only thing the constructor might do is confirm that it has the correct shape.  However, I'm not concerned with that here.

2023-08-21 22:29 UTC, DuHerb commented on src/index.ts
> +  users: ReadonlyMap<string, User>;
please make `UserAPI.users` private, so that it is not accessable to any other actors.

This mirrors the way persisted data should be handled.  Only API's with explicit permission should be able to interact with data.

2023-08-21 22:39 UTC, DuHerb commented on src/index.test.ts
> +    const actual = newUserApi.users.size;
confirm expected results by using the userApi.getUsers method, and other exposed methods.

2023-08-21 23:12 UTC, emmalgs commented on src/index.ts
> +  constructor(users: User[] = []) {
fixed

2023-08-21 23:13 UTC, emmalgs commented on src/index.ts
> +  readonly favColor: string,
addressed

2023-08-21 23:13 UTC, emmalgs commented on src/index.ts
> +  users: ReadonlyMap<string, User>;
fixed

2023-08-21 23:14 UTC, emmalgs commented on src/index.test.ts
> +    const actual = newUserApi.users.size;
fixed

2023-08-22 22:13 UTC, DuHerb requested changes

2023-08-22 22:13 UTC, DuHerb commented on src/index.ts
> +}
new line at end of file.  this is a github lint rule

2023-08-22 22:13 UTC, DuHerb commented on src/mockdata.ts
> +export default userRepo;
new line at end of file

2023-08-22 22:13 UTC, DuHerb commented on src/index.ts
> +  readonly favColor: string,
these properties are still 'readonly'

2023-08-22 22:15 UTC, emmalgs commented on src/index.ts
> +}
fixed

2023-08-22 22:15 UTC, emmalgs commented on src/mockdata.ts
> +export default userRepo;
fixed

2023-08-22 22:25 UTC, DuHerb approved these changes

2023-08-22 22:26 UTC, merged