Emma user api crud
olioapps/typescript-starter-lab pull request #64
Opened 2023-08-22 22:07 UTC by emmalgs

## What this is:
UserAPI CRUD
* complete CRUD methods for UserAPI class
* include addUser, deleteUserById, getUserById

## Ticket
[UserAPI CRUD](https://github.com/olioapps/typescript-starter-lab/issues/62)

## Steps to verify
* in the project directory on the branch 'emma-user-api-crud', run `yarn test`

## Media
![10 tests passing](https://github.com/olioapps/typescript-starter-lab/assets/40610781/35956b06-a729-4b01-ba2c-1e847f90c9c5)

2023-08-23 16:30 UTC, DuHerb requested changes

2023-08-23 16:30 UTC, DuHerb commented on src/index.ts
> +  assignId() {
Having 'helper' functions like `assignId` is great.  But these helpers don't need to be exposed.  So it should be marked as private.

This is one way to guard access to data and functionality.

2023-08-23 16:30 UTC, DuHerb commented on src/index.ts
> +  assignId() {
Naming nit pick.  `assignId` => `getUniqueId` or `generateUid`. Something that describes what the function is actually doing.

2023-08-23 16:30 UTC, DuHerb commented on src/index.ts
> +    this.currentId += 1;
`this.currentId +=1` is a reasonable first approach to providing a unique id/key.

But think about cases where `UserAPI` is instantiated with a set of users.  Those users already have ID's, and there are no checks here to guarantee that the new ID is actually unique.

There are many ways to generate UUIDs, but for our use case here, the simplist approach is to use a stringified timestamp. Try using the javascript `Date` api to generate the current time as a string, and use that as the id.

2023-08-23 16:30 UTC, DuHerb commented on src/index.ts
> +    return this.getAllUsers().filter((user) => user.id == id)[0];
you should be able to access `this.users` directly, using the `id` as the lookup value.

2023-08-23 16:30 UTC, DuHerb commented on src/index.ts
> +    delete this.users[id];
I'm making a new request here.  Please return the deleted user object.  This is a common pattern that you'll run into.  Often, an application will want to do something with some item that was just deleted -- IE: have the UI display information about that item.

2023-08-23 16:30 UTC, DuHerb commented on src/index.ts
> +    delete this.users[id];
Secondly, i would like you to use an immutable solution to this.  EG: don't operate directly on the `this.users` object.  using `delete` and `add` are probably very safe to use in this `UserAPI`.  But i'd like you to practice using immutable techniques.  use destructuring to remove the 'toBeDeletedUser'

EG: copy the existing state.  Transform/handle the copied state.  Return the handled copy as the new state.

2023-08-23 16:41 UTC, emmalgs commented on src/index.ts
> +  assignId() {
fixed

2023-08-23 16:42 UTC, emmalgs commented on src/index.ts
> +  assignId() {
fixed

2023-08-23 16:56 UTC, emmalgs commented on src/index.ts
> +    this.currentId += 1;
fixed -- needed to adjust some tests with this fix

2023-08-23 16:57 UTC, emmalgs commented on src/index.ts
> +    return this.getAllUsers().filter((user) => user.id == id)[0];
fixed!

2023-08-23 17:33 UTC, emmalgs commented on src/index.ts
> +    delete this.users[id];
fixed

2023-08-24 17:33 UTC, DuHerb requested changes

2023-08-24 17:33 UTC, DuHerb commented on src/mockdata.ts
> +export { userRepo, newUser };
new line at end of file.  We should be reviewing our PRs to catch lint errors like these before submitting for review.

2023-08-24 17:33 UTC, DuHerb commented on src/index.ts
> +  addUser(user: User): void {
many `create` type methods will require that the newly added object is returned.  The requesting client will likely wish to do something with the result.  IE: the client may need the new `id` to create some other resource.

go ahead and return the new object, and update your test so that it confirms that the new object has the expected properties.  name == expected name, id exists, etc.

2023-08-24 17:33 UTC, DuHerb commented on src/index.test.ts
> +    expect(actual).toEqual(expected);
confirm that the correct user was deleted by inspected the return properties.  Does it have the correct id?

2023-08-24 17:57 UTC, emmalgs commented on src/mockdata.ts
> +export { userRepo, newUser };
fixed

2023-08-24 18:01 UTC, emmalgs commented on src/index.ts
> +  addUser(user: User): void {
fixed

2023-08-24 18:03 UTC, emmalgs commented on src/index.test.ts
> +    expect(actual).toEqual(expected);
fixed

2023-08-25 16:32 UTC, DuHerb commented on src/index.ts
> +  deleteUserAtId(id: string): IdAwareUser {
`deleteUserById` is Olio convention for these types of functions.  `getUserById` `updateUserById` etc

2023-08-25 16:33 UTC, DuHerb approved these changes

2023-08-25 16:40 UTC, emmalgs commented on src/index.ts
> +  deleteUserAtId(id: string): IdAwareUser {
fixed

2023-08-25 16:54 UTC, merged