Emma eventstream puzzler tdd
olioapps/typescript-starter-lab pull request #74
Opened 2023-08-24 21:55 UTC by emmalgs

### What it is:
Tests for eventstream puzzler algorithm

### Ticket
[Eventstream Puzzler TDD](https://github.com/olioapps/typescript-starter-lab/issues/70)

### Steps to Verify
In the project directory on the branch 'emma-eventstream-puzzler-tdd' run `yarn test`

### Media
Failed tests:
![Screenshot 2023-08-24 at 2 55 13 PM](https://github.com/olioapps/typescript-starter-lab/assets/40610781/e66976ef-68a7-4482-a16d-4cf20a8ce1a3)
Coverage:
![Screenshot 2023-08-24 at 2 54 54 PM](https://github.com/olioapps/typescript-starter-lab/assets/40610781/dd4f7fb9-725f-4fe6-9dbf-86efd1781731)

2023-08-24 22:27 UTC, DuHerb requested changes

2023-08-24 22:27 UTC, DuHerb commented on src/mock_data.ts
> +const mistypedEventData: Array<EventObject> = [
rather than have 2 arrays that contain largley the same data set, i would just create a single array full of valid data.

Then, you can export a single 'bad' object and then just add it to the regular array in whatever test you need it.

2023-08-24 22:27 UTC, DuHerb commented on src/index.ts
> +  subregion: Array<EventObject>;
naming nit: `subregion` => `events`

The items ARE taken out of a larger array, but without that context, subregion doesnt' really describe what the values of that property actually are.

`subregion` is a name i would use for some placeholder value inside of the function that was handling the full event stream.

2023-08-24 22:27 UTC, DuHerb commented on src/index.ts
> +  eventType: string;
`eventType` needs to be typed.  There should only be three possible values that `eventType` can be.  Look up `unions` in typescript.

2023-08-24 22:27 UTC, DuHerb commented on src/index.ts
> +type EventObject = {
`EventObject` -> `Event`

2023-08-24 22:34 UTC, emmalgs commented on src/mock_data.ts
> +const mistypedEventData: Array<EventObject> = [
fixed

2023-08-24 22:36 UTC, emmalgs commented on src/index.ts
> +  subregion: Array<EventObject>;
fixed

2023-08-24 22:37 UTC, emmalgs commented on src/index.ts
> +  eventType: string;
fixed

2023-08-24 22:38 UTC, emmalgs commented on src/index.ts
> +type EventObject = {
fixed

2023-08-24 22:56 UTC, DuHerb requested changes

2023-08-24 22:56 UTC, DuHerb commented on src/index.test.ts
> +    const expected = "Region is larger than the list of events";
in this case, i would like the function to return the eventStream as if it were the highest scoring region.
EG:
if regionLength === 6, and eventStream.length === 4, then return all 4 events and their cummulative score.

2023-08-24 23:01 UTC, emmalgs commented on src/index.test.ts
> +    const expected = "Region is larger than the list of events";
fixed

2023-08-25 21:57 UTC, DuHerb commented on src/index.ts
> +  events: Array<Event>;
```suggestion
  events: EventSteam;
```

```
type EventStream = Array<Event>
```

2023-08-25 22:01 UTC, DuHerb approved these changes

2023-08-25 22:01 UTC, DuHerb commented on src/index.ts
> +// rename to scoreEventStream
remove dev comment

2023-08-25 22:01 UTC, DuHerb commented on src/index.ts
> +  events: Array<Event>;
```suggestion
  events: EventStream;
```

```
type EventStream = Array<Event>
```

2023-08-25 22:01 UTC, DuHerb commented on src/index.test.ts
> +  it("should return a scored event object", () => {
you could also break down the tests into additional `describe` blocks. One for tests about the expected score, and one for tests about the expected events.length

2023-08-25 22:04 UTC, DuHerb commented on src/index.test.ts
> +  it("should have a default region length of 5 if no region length is given", () => {
i would probably add a test to verify that the expected event objects are present in the return value

2023-08-25 22:58 UTC, emmalgs commented on src/index.ts
> +// rename to scoreEventStream
fixed

2023-08-25 22:58 UTC, emmalgs commented on src/index.ts
> +  events: Array<Event>;
fixed

2023-08-25 23:01 UTC, emmalgs commented on src/index.test.ts
> +  it("should return a scored event object", () => {
fixed

2023-08-25 23:07 UTC, emmalgs commented on src/index.test.ts
> +  it("should have a default region length of 5 if no region length is given", () => {
fixed

2023-08-25 23:14 UTC, merged